ExpenseManager/Models/ErrorViewModel.cs
using System;

namespace ExpenseManager.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExpenseManager/Models/Expense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Models
{
    public class Expense
    {
        [Key]
        public int Id { get; set; }
        [DisplayName("Expense")]
        [Required]
        public string ExpenseName { get; set; }
        
        [Range(1,Double.MaxValue, ErrorMessage ="Value should be greater than 0")]
        [Required]
        public double Amount { get; set; }
        public DateTime ExpenseDate { get; set; }

        public Expense()
        {
            ExpenseDate = DateTime.Now;
        }
    }
}

ExpenseManager/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        public string Borrower { get; set; }
        public string Lender { get; set; }
        [DisplayName("Item name")]
        public string ItemName { get; set; }
    }
}

ExpenseManager/Controllers/ExpenseController.cs
using ExpenseManager.Data;
using ExpenseManager.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ApplicationDBContext _db;
        public IActionResult Index()
        {
            IEnumerable<Expense> objList = _db.Expenses;
            return View(objList);
        }
        //Get Create
        public IActionResult Create()
        {
            return View();
        }
        //Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Expense obj)
        {
            if(ModelState.IsValid)
            {
                _db.Expenses.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //Get Delete
        public IActionResult Delete(int? id)
        {
            if(id==null||id==0)
            {
                return NotFound();
            }
            Expense obj = _db.Expenses.Find(id);
            if(obj==null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            Expense obj = _db.Expenses.Find(id);
            if(obj==null)
            {
                return NotFound();
            }
            _db.Expenses.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");     
        }

        //Get Update
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Expense obj = _db.Expenses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //Post Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Expense obj)
        {
            if (ModelState.IsValid)
            {
                _db.Expenses.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public ExpenseController(ApplicationDBContext db)
        {
            _db = db;
        }
    }
}

ExpenseManager/Controllers/HomeController.cs
using ExpenseManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExpenseManager/Controllers/ItemController.cs
using ExpenseManager.Data;
using ExpenseManager.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDBContext _db;
        public IActionResult Index()
        {
            IEnumerable<Item> objList = _db.Items;
            return View(objList);
        }
        //Get Create
        public IActionResult Create()
        {
            return View();
        }
        //Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item obj)
        {
            _db.Items.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ItemController(ApplicationDBContext db)
        {
            _db = db;
        }

        //Get Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Item obj = _db.Items.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            Item obj = _db.Items.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Items.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ExpenseManager/Views/Expense/Create.cshtml
@model ExpenseManager.Models.Expense

<form method="post" asp-action="create">
    <div class="border pt-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ExpenseName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ExpenseName" class="form-control" />
                        <span asp-validation-for="ExpenseName" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create" />
                        </div>
                        <div class="col">
                            <a class="nav-link text-dark btn btn-danger w-75" asp-action="Index">Go back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

ExpenseManager/Views/Expense/Delete.cshtml
@model ExpenseManager.Models.Expense

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border pt-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-4">Delete expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row pl-3 pr-3">
                    <div class="col-4">
                        <label asp-for="ExpenseName"></label>
                        <input asp-for="ExpenseName" disabled class="form-control" />
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                        <input type="number" asp-for="Amount" disabled class="form-control" />
                    </div>
                    <div class="col-4">
                        <label asp-for="ExpenseDate"></label>
                        <input asp-for="ExpenseDate" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a class="nav-link btn btn-info w-75" asp-action="Index">Go back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

ExpenseManager/Views/Expense/Index.cshtml
@model IEnumerable<ExpenseManager.Models.Expense>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Borrowed Item List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Expense" asp-action="Create" class="btn btn-primary">Create New Expense</a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Expense Name
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Date
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="20%">@item.ExpenseName</td>
                        <td width="20%">@item.Amount</td>
                        <td width="20%">@item.ExpenseDate</td>
                        <td width="40%" >
                            <div class="text-right w-100 btn-group" role="group">
                                <a asp-controller="Expense" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-primary mx-1">Update</a>
                                <a asp-controller="Expense" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-danger mx-1">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No expenses added yet</p>
    }

</div>

ExpenseManager/Views/Expense/Update.cshtml
@model ExpenseManager.Models.Expense

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden/>
    <div class="border pt-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-5">Update expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row justify-content-around pl-3 pr-3">
                    <div class="col-6">
                        <label asp-for="ExpenseName"></label>
                        <input asp-for="ExpenseName" class="form-control" />
                        <span asp-validation-for="ExpenseName" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <label asp-for="Amount"></label>
                        <input type="number" asp-for="Amount"  class="form-control" />
                        <span asp-validation-for="ExpenseName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a class="nav-link text-dark btn btn-danger w-100" asp-action="Index">Go back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

ExpenseManager/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="text-black-50">Expense and Item manager</h1>
    <p>An MVC project created to learn basics of .NET Core MVC</p>
    <p>It contains 2 functional pages: Items and Expenses. You can add, delete and edit them as in a typical CRUD app.</p>
</div>

ExpenseManager/Views/Item/Create.cshtml
@model ExpenseManager.Models.Item

<form method="post" asp-action="create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ItemName"></label>
                        <input asp-for="ItemName" class="form-control" />
                    </div>
                    <div class="col-4">
                        <label asp-for="Borrower"></label>
                        <input asp-for="Borrower" class="form-control" />
                    </div>
                    <div class="col-4">
                        <label asp-for="Lender"></label>
                        <input asp-for="Lender" class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create"/>
                        </div>
                        <div class="col">
                            <a class="nav-link text-dark btn btn-danger w-75" asp-action="Index">Go back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

ExpenseManager/Views/Item/Delete.cshtml
@model ExpenseManager.Models.Item

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border pt-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-4">Delete item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row pl-3 pr-3">
                    <div class="col-4">
                        <label asp-for="ItemName"></label>
                        <input asp-for="ItemName" disabled class="form-control" />
                    </div>
                    <div class="col-4">
                        <label asp-for="Lender"></label>
                        <input asp-for="Lender" disabled class="form-control" />
                    </div>
                    <div class="col-4">
                        <label asp-for="Borrower"></label>
                        <input asp-for="Borrower" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a class="nav-link btn btn-info w-75" asp-action="Index">Go back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

ExpenseManager/Views/Item/Index.cshtml
@model IEnumerable<ExpenseManager.Models.Item>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Borrowed Item List</h2>
        </div>
        <div class="col-6 text-right"> 
            <a asp-controller="Item" asp-action="Create" class="btn btn-primary">Create New Item</a>
        </div>
    </div>
    <br />

    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Item Name
                    </th>
                    <th>
                        Borrower
                    </th>
                    <th>
                        Lender
                    </th>
                    <th>
                        Controls
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                <tr>
                    <td width="25%">@item.ItemName</td>
                    <td width="25%">@item.Borrower</td>
                    <td width="25%">@item.Lender</td>
                    <td width="25%" class="text-center">
                        <a asp-controller="Item" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-danger w-75 mx-1">Delete</a>
                    </td>      
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No items added yet</p>
    }

</div>

ExpenseManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExpenseManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">My Borrowed Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">My Expenses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExpenseManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>